"""run 113: حارس القرار ٤ — صيغ كانت تمرّ (تدقيق عدائي /tmp/g113/probe.py): حروف تنسيق غير مرئية/RLO، يونانية/شيروكي، كيانات
HTML ووسوم داخل الكلمة، LaTeX، leetspeak، «62k»، أفعال عامّية، أسماء الأزواج، المتكلّم، سؤال وجواب، لغات جديدة
(روسية/صينية/هندية/فارسية/أردية/إيطالية/برتغالية/إندونيسية)، لهجات وكردية. وجمل تعليمية يجب ألّا تُحذف."""
import pytest

import openrouter_ai as oa

LEAK = [
    'B\u200cuy EURUSD now',
    'S\u200cell gold here',
    'B\u200fuy EURUSD now',
    'Se\u200ell gold now',
    'B\u2066uy\u2069 EURUSD now',
    '\u202eYUB\u202c EURUSD',
    'Sto\u200fp loss 1.0800',
    'Tar\u200cget 1.0950',
    'En͏try 1.0850',
    'B\u2062uy at 1.0850',
    'Bu̲y EURUSD now',
    'Búy EURUSD now',
    'S̶e̶l̶l̶ gold now',
    'ΒUY EURUSD now',
    'LΟNG EURUSD now',
    'ᏴUY EURUSD now',
    '𝐁𝐮𝐲 EURUSD now',
    '𝗦𝗲𝗹𝗹 gold now',
    'ᴮᵁʸ EURUSD now',
    'Buy at 1·0850',
    'Sell at 1⋅0900',
    'Buy at 1‘0850',
    'Buy at १.०८५०',
    'Buy EURUSD at ①.⓪⑧⑤⓪',
    '5ELL gold now',
    'L0NG EURUSD now',
    'SH0RT gold now',
    '8UY EURUSD now',
    'Buuuy EURUSD now',
    'BUYYY gold now',
    '&#66;uy EURUSD now',
    '&#x42;UY EURUSD',
    'Buy&nbsp;EURUSD&nbsp;now',
    'Entry&#58; 1&#46;0850',
    'Buy at 1&period;0850',
    'B<span>uy</span> EURUSD now',
    'Bu<!-- -->y EURUSD now',
    'Entry: <b>1</b>.0850',
    'Sell at <b>1</b>.0900',
    '[Buy](#) EURUSD',
    'B_U_Y EURUSD now',
    'S_E_L_L gold',
    'B/U/Y EURUSD',
    'T a r g e t 1.0950',
    'S t o p l o s s 1.0800',
    '$\\textbf{Long}$ EURUSD',
    'Buy BTC at 65k.',
    'Buy BTC under 65K.',
    'SL 62k',
    'TP 70k',
    'Stop 62K on BTC',
    'Target 70 for oil.',
    'Target $80 on oil.',
    'Buy oil at $65.',
    'Sell oil at 80 bucks.',
    'Buy silver at 28.',
    'Entry 28 on silver.',
    'Short BTC around 70k, cover at 62k.',
    'Purchase EURUSD at 1.0850.',
    'Acquire gold at 2350.',
    'Bid EURUSD at 1.0850.',
    'Bid it at 1.0850.',
    'Offer gold at 2400.',
    'Offer it at 1.0900.',
    'Offload gold at 2400.',
    'Trim at 1.0950.',
    'Trim the position at 1.0950.',
    'Peel off some at 1.0950.',
    'Cash out at 1.0950.',
    'Pay yourself at 1.0950.',
    'Realise profits at 1.0950.',
    'Harvest gains at 1.0950.',
    'Ring the register at 1.0950.',
    'Shoot for 1.0950.',
    'Your line in the sand is 1.0800.',
    "I'm wrong below 1.0800.",
    'The idea is void below 1.0800.',
    'Thesis dies under 1.0800.',
    'Risk down to 1.0800.',
    'Walk away on a close under 1.0800.',
    'Press it lower from 1.0900.',
    'Get some exposure at 1.0850.',
    "I'd want exposure from 1.0850.",
    'Own EURUSD above 1.0850.',
    'Own gold here.',
    'Go overweight EURUSD.',
    'Overweight gold here.',
    'Join the bulls at 1.0850.',
    'Go bullish on EURUSD at 1.0850.',
    'The long side from 1.0850 looks good.',
    'Lean on 1.0900 from the short side.',
    'Worth a punt on the upside from 1.0850.',
    'Upside exposure from 1.0850 makes sense.',
    'Rest a limit at 1.0850.',
    'Work a bid at 1.0850.',
    'Long the fiber at 1.0850.',
    'Short cable at 1.2700.',
    'Short the Aussie here.',
    'Sell Cable here.',
    'Buy the Swissy.',
    'Sell the greenback.',
    'Buy eurusd.',
    'Sell xauusd.',
    'Sell Brent.',
    'Buy Nasdaq.',
    'Buy the S&P.',
    'Buy Ether.',
    'Buy the loonie here.',
    "If we get 1.0850, I'm in.",
    'Should 1.0850 hold, count me in.',
    "I'm a buyer above 1.0900.",
    "We're sellers at 1.0900.",
    'Buyer above 1.0900.',
    'Seller below 1.0800.',
    "Bullish above 1.0850 — that's where I'd get involved.",
    "At 1.0850 I'm in, at 1.0950 I'm out.",
    "Dip to 1.0850? That's my cue.",
    'Count me long.',
    'Q: Should I buy EURUSD?\nA: Yes.',
    'Q: Should I buy EURUSD? A: Yes, I would.',
    'Is it a buy? In my view, yes.',
    'Would I buy here? Yes.',
    'Should you sell gold? I would.',
    'Q: Where would you get out?\nA: 1.0950.',
    'Q: Direction?\nA: Up — buy it.',
    'Long or short? The former.',
    'Buy or sell? Definitely the first.',
    '{"px_in": 1.0850, "px_out": 1.0950}',
    '{"bid": 1.0850, "exit": 1.0950}',
    '{"side":"B","px":1.0850}',
    'B,EURUSD,1.0850,1.0800,1.0950',
    'in=1.0850 out=1.0950 cut=1.0800',
    '<order side="buy" price="1.0850"/>',
    'BID 1.0850 | OUT 1.0950',
    'Plan: bid 1.0850, bail 1.0800, cash out 1.0950.',
    'For example, on your EURUSD chart right now: a bullish position from 1.0850, wrong below 1.0800.',
    'Hypothetically, a trader on this chart would be a buyer near 1.0850.',
    'Entrez long à 1,0850.',
    "Positionnez-vous à la hausse sur l'EURUSD.",
    "Shortez l'EURUSD à 1,0900.",
    'Prise de bénéfices à 1,0950.',
    'Seuil de sortie 1,0950.',
    'Entra en largo en 1.0850.',
    'Ponte corto en el oro.',
    'Abre cortos en 1.0900.',
    'Toma de ganancias en 1.0950.',
    'Compre agora.',
    'Venda agora o ouro.',
    'Compra ora EURUSD.',
    'Vendi a 1,0900.',
    'Obiettivo 1,0950.',
    'Stopp bei 1,0800.',
    'Long gehen bei 1,0850.',
    'Gewinnmitnahme bei 1,0950.',
    'Verlustbegrenzung 1,0800.',
    'Kaufen Sie EURUSD.',
    'Zarar kes 1.0800.',
    'Long pozisyon aç.',
    'EURUSD al.',
    'Satış yap.',
    'Şimdi al.',
    'Покупайте EURUSD.',
    'Стоп-лосс 1.0800',
    'Тейк-профит 1.0950',
    'Вход 1.0850',
    'Продавайте золото сейчас.',
    '在1.0850买入',
    '止损1.0800',
    '止盈1.0950',
    '目标位1.0950',
    '做空黄金',
    'अभी खरीदें',
    'स्टॉप लॉस 1.0800',
    'Beli sekarang',
    'Jual di 1.0900',
    'بخرید در ۱٫۰۸۵۰',
    'حد ضرر ۱٫۰۸۰۰',
    'حد سود ۱٫۰۹۵۰',
    'نقطه ورود ۱٫۰۸۵۰',
    'الان بخرید',
    'خرید کنید',
    'بفروشید',
    'ابھی خریدیں',
    'سٹاپ لاس 1.0800',
    'ٹارگٹ 1.0950',
    'خریداری کریں 1.0850 پر',
    'فروخت کریں',
    'استهدف 1.0950',
    'نستهدف ١٫٠٩٥٠',
    'نقطة الانطلاق للصفقة 1.0850',
    'سعر التنفيذ المقترح 1.0850',
    'اجعل حمايتك تحت 1.0800',
    'اخرج بربح عند 1.0950',
    'اخرج عند 1.0950',
    'صفقة شرائية من 1.0850',
    'مركز شرائي عند 1.0850',
    'تمركز شرائي قرب ١٫٠٨٥٠',
    'خروج جزئي عند 1.0950',
    'شراء 1.0850',
    'شراء ليمت 1.0850',
    'الذهب؟ اشتريه من 1.0850',
    'فكّر بالدخول الآن',
    'خذ لك صفقة شرا من 1.0850',
    'شرا من 1.0850',
    'اضرب شرا',
    'فوت شرا',
    'هات شراء',
    'قفّل على مكسب عند 1.0950',
    'دخل فالشرا من 1.0850',
    'باي ليمت 1.0850',
    'باي من 1.0850',
    'سيل من 1.0900',
    'لونج من 1.0850',
    'شورت على الذهب',
    'اشتريه هلق',
    'بيعه من 1.0900',
    'eshtery delwa2ty',
    'eshtiri men 1.0850',
    'ishtree el dahab',
    'shtri men 1.0850',
    'da5la mn 1.0850',
    'shoof 1.0850 w eshtery',
    'bi3o men 1.0900',
    'ed5ol shera2 3and 1.0850',
    'بیکرە ئێستا',
    'کرین لە 1.0850',
    'ستوپ لە 1.0800',
    'تارگێت 1.0950',
    'ڕاگرتنی زیان 1.0800',
    'قازانج وەرگرتن لە 1.0950',
    'خاڵی دەرچوون 1.0950',
    'ئێستا کاتی کڕینە',
    'Kirîn li 1.0850',
    'Firotin li 1.0900',
    'Stopa windabûnê 1.0800',
    'Têkeve li 1.0850',
    'Bikeve bazarê niha',
    'Buy عالدعم',
    'Buy هون',
    'Sell هلأ',
    'لونج EURUSD',
    'شورت gold من 1.0900',
    'Long ئێستا',
    'خرید EURUSD now',
]

OK = [
    'Buy-side liquidity rests above equal highs.',
    'Sell-side liquidity sits below equal lows.',
    'A stop-loss is an order that exits a trade at a predefined price to cap the loss.',
    'A take-profit order closes a winning trade at a chosen level.',
    'RSI above 70 is commonly read as overbought.',
    'RSI 30 is the classic oversold threshold.',
    'The 14-period RSI was introduced by Welles Wilder in 1978.',
    'The 200-day moving average is widely followed by institutions.',
    'In 2015 the Swiss National Bank removed the EURCHF floor at 1.20.',
    'On Black Wednesday in 1992, sterling left the ERM.',
    'EURUSD peaked near 1.60 in 2008.',
    'Gold hit a record above 2,000 in 2020.',
    'Bitcoin traded near 69k in November 2021.',
    'The trade balance is the difference between exports and imports.',
    'Long-term investors often ignore daily noise.',
    'Short-term charts contain more noise than daily charts.',
    'A long upper wick shows sellers rejected higher prices.',
    'Shorts covering can fuel a sharp rally.',
    'A short squeeze happens when short sellers rush to buy back.',
    'The bid is what buyers pay; the offer is what sellers ask.',
    'Offer and bid together form the quote.',
    'A limit order rests in the book until filled.',
    'Market makers work bids and offers all day.',
    'Trimming a position means reducing its size.',
    'Cashing out too early is a common psychological mistake.',
    'Overweight and underweight are portfolio allocation terms.',
    'The fiber is a nickname for EURUSD; cable is GBPUSD.',
    'The Aussie is the Australian dollar.',
    'Purchasing power parity compares currencies through a basket of goods.',
    "A buyer's market favours buyers; a seller's market favours sellers.",
    'Exposure is the amount of capital at risk in the market.',
    'The line in the sand is a phrase for a key level traders watch.',
    'Max pain theory relates to options expiry.',
    'Risk management decides how much you can lose before you are wrong.',
    'Invalidation defines when a trading idea is no longer valid.',
    'Q: What is a stop-loss? A: An order that limits your loss.',
    'Q: Should beginners use leverage? A: Very carefully, if at all.',
    'Is it a good idea to trade news? Many beginners find it too volatile.',
    'Long or short positions both carry risk.',
    'Buy or sell decisions should follow a written plan.',
    'JSON fields like side, price and qty describe an order.',
    'A CSV export may include columns like date, open, high, low, close.',
    'Open, high, low and close are the four prices of a candle.',
    'The open was at 1.0850 and the close at 1.0870 yesterday.',
    'Le stop-loss est un ordre qui limite la perte.',
    'El stop loss protege tu capital.',
    'Der Stop-Loss begrenzt den Verlust.',
    'Stop-loss nedir? Zararı sınırlayan bir emirdir.',
    'Стоп-лосс — это ордер, ограничивающий убыток.',
    '止损是一种限制亏损的订单。',
    'حد ضرر سفارشی است که زیان را محدود می\u200cکند.',
    'وقف الخسارة أداة لإدارة المخاطر وليس توصية.',
    'المشترون تدخلوا عند 1.0850 الأسبوع الماضي.',
    'الشراء بالهامش يعني الاقتراض لزيادة حجم المركز.',
    'مؤشر RSI عند ٧٠ يعني تشبعاً شرائياً.',
    'ستۆپ لۆس ڕێگایەکە بۆ کەمکردنەوەی زیان.',
    'Stop-loss rêyek e ji bo sînorkirina ziyanê.',
    'The 50 and 200 EMAs are popular trend filters.',
    'A 1:3 risk-reward ratio means the target is three times the risk.',
    'Price made a higher high at 1.0950 last Tuesday.',
    "Traders talk about 'buying the dip' in bull markets.",
    'The fear and greed index ranges from 0 to 100.',
    'Volume rose 30% during the London open.',
    'Bullish divergence occurs when price makes a lower low but RSI makes a higher low.',
    "The term 'bagholder' describes someone stuck in a losing position.",
    'A trailing stop moves with price to protect open profit.',
]


@pytest.mark.parametrize("text", LEAK)
def test_trade_call_is_removed(text):
    out = oa.guard_answer("RSI is 55.\n" + text, "en")
    assert text not in out and "RSI is 55." in out


@pytest.mark.parametrize("text", OK)
def test_educational_text_is_kept(text):
    assert not oa.has_trade_call(text)
    assert oa.guard_answer(text, "en") == text


def test_turkish_and_french_accents_still_match_in_first_variant():
    assert oa.has_trade_call("Sat şimdi") and oa.has_trade_call("Entrée 1.0850")
